# Generated by Django 3.0.6 on 2020-06-22 16:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200622_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
