# Generated by Django 3.0.6 on 2020-06-22 16:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200622_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, max_length=500),
        ),
    ]
