# Generated by Django 3.0.8 on 2020-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20200816_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
