# Generated by Django 3.0.8 on 2020-08-19 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20200819_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='pre_completion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_completion', to='learn.Completion'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pre_lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_lesson', to='learn.Lesson'),
        ),
    ]
