# Generated by Django 3.0.8 on 2020-12-18 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0016_auto_20201201_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('short_description', models.CharField(blank=True, max_length=60)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='programs/images/')),
                ('members', models.ManyToManyField(blank=True, to='main.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', froala_editor.fields.FroalaField()),
                ('short_description', models.CharField(blank=True, max_length=60)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='programs/images/')),
                ('members', models.ManyToManyField(blank=True, to='main.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='programs/images/')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('facilitator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Facilitator')),
                ('members', models.ManyToManyField(blank=True, to='main.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facilitator',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='facilitators', to='programs.Program'),
        ),
    ]
