# Generated by Django 3.0.6 on 2020-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='image',
            field=models.ImageField(blank=True, upload_to='programs/images/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, upload_to='programs/images/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, upload_to='programs/images/'),
        ),
    ]
