# Generated by Django 3.0.8 on 2020-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20200718_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
