# Generated by Django 3.0.8 on 2020-08-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20200720_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='facilitators', to='programs.Program'),
        ),
    ]
