# Generated by Django 3.0.8 on 2020-08-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_auto_20200816_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='short_description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='program',
            name='short_description',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
