# Generated by Django 3.0.8 on 2020-08-16 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='predecessor',
            field=models.ManyToManyField(blank=True, to='learn.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='memberss', through='learn.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
