# Generated by Django 3.0.8 on 2020-08-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20200816_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completion',
            old_name='start',
            new_name='start_date',
        ),
    ]
