# Generated by Django 3.0.8 on 2020-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20200816_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='challeng_link',
        ),
        migrations.AddField(
            model_name='completion',
            name='challeng_answer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
