# Generated by Django 3.0.8 on 2020-08-16 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0005_auto_20200816_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='learn/images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(related_name='members', through='learn.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
