# Generated by Django 3.0.8 on 2020-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_course_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hebrew',
            field=models.BooleanField(default=False),
        ),
    ]
