# Generated by Django 3.0.8 on 2020-08-19 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_course_hebrew'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='pre_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coming_completion', to='learn.Completion', unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pre_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coming_lesson', to='learn.Lesson', unique=True),
        ),
    ]
