# Generated by Django 3.0.8 on 2020-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_auto_20200819_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completion',
            options={'ordering': ['lesson']},
        ),
        migrations.AlterField(
            model_name='course',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
