# Generated by Django 3.0.8 on 2020-08-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_auto_20200828_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='last_completion',
        ),
    ]
