from django.urls import path
from . import views

app_name='programs'

urlpatterns = [
    path('program/', views.ProgramListView.as_view(),
         name='program_list'),
    path('program/create', views.ProgramCreateView.as_view(),
         name='program_create'),
    path('program/<int:pk>', views.ProgramDetailView.as_view(),
         name='program_detail'),
    path('program/update/<int:pk>', views.ProgramUpdateView.as_view(),
         name='program_update'),
    path('program/delete/<int:pk>', views.ProgramDeleteView.as_view(),
         name='program_delete'),
    path('program/add_member/<int:program_id>/<int:profile_id>',
         views.program_add_member,
         name='program_add_member'),
    path('program/remove_member/<int:program_id>/<int:profile_id>',
         views.program_remove_member,
         name='program_remove_member'),
    path('program/add_school/<int:source_program>/',
        views.ProgramAddSchoolList.as_view(),
        name='program_add_school'),
    path('program/add_school/<int:source_program>/<int:dest_facilitator>',
        views.program_add_school_action,
        name='program_add_school_action'),
    path('program/delete_school/<int:source_program>/<int:dest_facilitator>',
         views.program_delet_school_action,
         name='program_delet_school_action'),

    path('facilitator/', views.FacilitatorListView.as_view(),
         name='facilitator_list'),
    path('facilitator/create', views.FacilitatorCreateView.as_view(),
         name='facilitator_create'),
    path('facilitator/<int:pk>', views.FacilitatorDetailView.as_view(),
         name='facilitator_detail'),
    path('facilitator/update/<int:pk>', views.FacilitatorUpdateView.as_view(),
         name='facilitator_update'),
    path('facilitator/delete/<int:pk>', views.FacilitatorDeleteView.as_view(),
         name='facilitator_delete'),
    path('facilitator/add_member/<int:facilitator_id>/<int:profile_id>',
         views.facilitator_add_member,
         name='facilitator_add_member'),
    path('facilitator/remove_member/<int:facilitator_id>/<int:profile_id>',
         views.facilitator_remove_member,
         name='facilitator_remove_member'),
    path('facilitator/add_program/<int:source_facilitator>/',
        views.FacilitatorAddProgramList.as_view(),
        name='facilitator_add_program'),
    path('facilitator/add_program/<int:source_facilitator>/<int:dest_program>',
        views.facilitator_add_program_action,
        name='facilitator_add_program_action'),
    path('facilitator/delete_program/<int:source_facilitator>/<int:dest_program>',
         views.facilitator_delet_program_action,
         name='facilitator_delet_program_action'),
]
